[2025-05-22T21:48:34.526+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_insert_bank_reviews.copy_tables_to_remote manual__2025-05-19T10:58:39.511715+00:00 [queued]>
[2025-05-22T21:48:34.542+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_insert_bank_reviews.copy_tables_to_remote manual__2025-05-19T10:58:39.511715+00:00 [queued]>
[2025-05-22T21:48:34.544+0100] {taskinstance.py:2170} INFO - Starting attempt 6 of 6
[2025-05-22T21:48:34.569+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): copy_tables_to_remote> on 2025-05-19 10:58:39.511715+00:00
[2025-05-22T21:48:34.581+0100] {standard_task_runner.py:60} INFO - Started process 27040 to run task
[2025-05-22T21:48:34.592+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_and_insert_bank_reviews', 'copy_tables_to_remote', 'manual__2025-05-19T10:58:39.511715+00:00', '--job-id', '1956', '--raw', '--subdir', 'DAGS_FOLDER/S_G_M_R.py', '--cfg-path', '/tmp/tmpql4cjgun']
[2025-05-22T21:48:34.595+0100] {standard_task_runner.py:88} INFO - Job 1956: Subtask copy_tables_to_remote
[2025-05-22T21:48:34.779+0100] {task_command.py:423} INFO - Running <TaskInstance: scrape_and_insert_bank_reviews.copy_tables_to_remote manual__2025-05-19T10:58:39.511715+00:00 [running]> on host DESKTOP-RRUTCI2.
[2025-05-22T21:48:35.292+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_and_insert_bank_reviews' AIRFLOW_CTX_TASK_ID='copy_tables_to_remote' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T10:58:39.511715+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T10:58:39.511715+00:00'
[2025-05-22T21:48:35.296+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'dim_bank' from local schema 'public_decision_schema'...
[2025-05-22T21:48:35.480+0100] {logging_mixin.py:188} INFO - bank_id       int64
bank_name    object
dtype: object
[2025-05-22T21:48:35.482+0100] {logging_mixin.py:188} INFO - ‚¨ÜÔ∏è Uploading 'dim_bank' to remote (replace if exists)...
[2025-05-22T21:48:37.424+0100] {logging_mixin.py:188} INFO - ‚úÖ 'dim_bank' copied and replaced successfully.
[2025-05-22T21:48:37.428+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'dim_branch' from local schema 'public_decision_schema'...
[2025-05-22T21:48:37.500+0100] {logging_mixin.py:188} INFO - branch_id        int64
branche_name    object
dtype: object
[2025-05-22T21:48:37.506+0100] {logging_mixin.py:188} INFO - ‚¨ÜÔ∏è Uploading 'dim_branch' to remote (replace if exists)...
[2025-05-22T21:48:38.560+0100] {logging_mixin.py:188} INFO - ‚úÖ 'dim_branch' copied and replaced successfully.
[2025-05-22T21:48:38.563+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'dim_location' from local schema 'public_decision_schema'...
[2025-05-22T21:48:38.597+0100] {logging_mixin.py:188} INFO - location_id     int64
address        object
dtype: object
[2025-05-22T21:48:38.600+0100] {logging_mixin.py:188} INFO - ‚¨ÜÔ∏è Uploading 'dim_location' to remote (replace if exists)...
[2025-05-22T21:48:39.617+0100] {logging_mixin.py:188} INFO - ‚úÖ 'dim_location' copied and replaced successfully.
[2025-05-22T21:48:39.622+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'dim_sentiment' from local schema 'public_decision_schema'...
[2025-05-22T21:48:39.688+0100] {logging_mixin.py:188} INFO - sentiment_id        int64
sentiment_label    object
dtype: object
[2025-05-22T21:48:39.691+0100] {logging_mixin.py:188} INFO - ‚¨ÜÔ∏è Uploading 'dim_sentiment' to remote (replace if exists)...
[2025-05-22T21:48:40.760+0100] {logging_mixin.py:188} INFO - ‚úÖ 'dim_sentiment' copied and replaced successfully.
[2025-05-22T21:48:40.763+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'fact_reviews' from local schema 'public_decision_schema'...
[2025-05-22T21:48:40.834+0100] {logging_mixin.py:188} INFO - bank_id            int64
branch_id          int64
location_id        int64
sentiment_id       int64
review_date       object
scrapping_date    object
review_text       object
topic_meaning     object
topic_words       object
rating            object
dtype: object
[2025-05-22T21:48:40.836+0100] {logging_mixin.py:188} INFO - ‚¨ÜÔ∏è Uploading 'fact_reviews' to remote (replace if exists)...
[2025-05-22T21:48:42.035+0100] {logging_mixin.py:188} INFO - ‚úÖ 'fact_reviews' copied and replaced successfully.
[2025-05-22T21:48:42.038+0100] {logging_mixin.py:188} INFO - üîÑ Reading 'clean_bank_reviews' from local schema 'public'...
[2025-05-22T21:48:42.046+0100] {logging_mixin.py:188} INFO - ‚ùå Error copying 'clean_bank_reviews': Could not reflect: requested table(s) not available in Engine(postgresql+psycopg2://airflow_user:***@localhost:5432/airflow_db) schema 'public': (clean_bank_reviews)
[2025-05-22T21:48:42.258+0100] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2025-05-22T21:48:42.260+0100] {logging_mixin.py:188} WARNING -   File "/home/osama/airflow/dags/S_G_M_R.py", line 545, in copy_tables_to_remote
    df = pd.read_sql_table(table, con=local_engine, schema=source_schema)
[2025-05-22T21:48:42.262+0100] {logging_mixin.py:188} WARNING -   File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 340, in read_sql_table
    table = pandas_sql.read_table(
[2025-05-22T21:48:42.265+0100] {logging_mixin.py:188} WARNING -   File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1627, in read_table
    self.meta.reflect(bind=self.con, only=[table_name])
[2025-05-22T21:48:42.271+0100] {logging_mixin.py:188} WARNING -   File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4889, in reflect
    raise exc.InvalidRequestError(
[2025-05-22T21:48:42.274+0100] {logging_mixin.py:188} WARNING - sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql+psycopg2://airflow_user:***@localhost:5432/airflow_db) schema 'public': (clean_bank_reviews)
[2025-05-22T21:48:42.276+0100] {python.py:201} INFO - Done. Returned value was: None
[2025-05-22T21:48:42.319+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=scrape_and_insert_bank_reviews, task_id=copy_tables_to_remote, execution_date=20250519T105839, start_date=20250522T204834, end_date=20250522T204842
[2025-05-22T21:48:42.390+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-22T21:48:42.450+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
